apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-typescript
  title: example-typescript
  description: An example typescript for Codecov validation
  annotations:
    github.com/project-slug: roadie-demo/example-typescript
    backstage.io/techdocs-ref: dir:. 
  links:
    - title: Test Plan
      url: https://roadie.io
      type: test-plan
    
spec:
  type: service
  owner: group:roadie-demo/solutions
  lifecycle: production

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: typescript-s3-bucket
  description: The s3 bucket with the typescript data in it. Doesn't really exist.
spec:
  type: s3-bucket
  owner: group:roadie-demo/engineering
  system: typescript-system
  tier: 0

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: typescript-domain
  description: typescript things to teleprompt.
spec:
  owner: group:roadie-demo/engineering
  lifecycle: production
  system: typescript-system
  dependsOn:
    - Resource:typescript-s3-bucket

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  title: typescript System
  name: typescript-system
  description: typescript things to teleprompt.
spec:
  owner: group:roadie-demo/engineering
  domain: typescript-domain