site_name: Root docs
repo_url: https://github.com/roadie-demo/example-typescript
edit_uri: edit/main/docs

nav:
  - Home: index.md

plugins:
  - techdocs-core

markdown_extensions:
  - mkdocs_graphviz